# frozen_string_literal: true

source 'https://rubygems.org'

plugin 'diffend'

# ActiveSupport and rexml are only used for XML support
gem 'activesupport'
gem 'rake'
gem 'rexml'

gem 'karafka', '>= 2.0.0.alpha2'

group :development, :test do
  gem 'byebug', platform: :ruby
  gem 'karafka-testing', '>= 2.0.0.alpha3'
  gem 'rspec'
  gem 'simplecov'
end
