# frozen_string_literal: true

source 'https://rubygems.org'

plugin 'diffend'

# ActiveSupport and rexml are only used for XML support
gem 'activesupport'
gem 'rexml'

gem 'karafka', '~> 1.4'
gem 'karafka-sidekiq-backend', '~> 1.4'

group :development, :test do
  gem 'byebug', platform: :ruby
  gem 'karafka-testing', '~> 1.4'
  gem 'rspec'
  gem 'simplecov'
end
