# frozen_string_literal: true

source 'https://rubygems.org'

gem 'karafka', '>= 2.4.0.rc1'
gem 'karafka-web', '>= 0.9.0.rc3'
gem 'puma'
gem 'rails', '~> 7.1'
gem 'sqlite3', '1.7.3'

group :development, :test do
  gem 'karafka-testing', '>= 2.4.0.rc2'
  gem 'rspec'
end
