# frozen_string_literal: true

source 'https://rubygems.org'

gem 'karafka'
gem 'karafka-web'
gem 'puma'
gem 'rails', '~> 7.1'
gem 'sqlite3', '2.4.0'

group :development, :test do
  gem 'karafka-testing'
  gem 'rspec'
end
