# lostconf configuration
# Exclude symlinked directories to avoid duplicate/false positives
# v2.3 and v2.4 are symlinks to v2.5
exclude:
  - v2.3-non-rails
  - v2.3-rails
  - v2.4-non-rails
  - v2.4-rails
