# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '6.0.3.2'
gem 'karafka', '1.3.6'
gem 'karafka-sidekiq-backend', '1.3.1'

group :development, :test do
  gem 'byebug', platform: :ruby
  gem 'rspec'
  gem 'simplecov', '0.18.5'
end
