# frozen_string_literal: true

source 'https://rubygems.org'

plugin 'diffend'

gem 'karafka', '>= 2.1.5'
gem 'karafka-web'
gem 'puma'
gem 'rails', '~> 7.0'
gem 'sqlite3', '~> 1.4'

group :development, :test do
  gem 'karafka-testing'
  gem 'rspec'
end
