# frozen_string_literal: true

source 'https://rubygems.org'

plugin 'diffend'

# ActiveSupport and rexml are only used for XML support
gem 'activesupport'
gem 'rake'
gem 'rexml'

gem 'karafka', github: 'karafka/karafka', branch: '2.0'

group :development, :test do
  gem 'byebug'
  gem 'karafka-testing', github: 'karafka/testing'
  gem 'rspec'
  gem 'simplecov'
end
