# frozen_string_literal: true

source 'https://rubygems.org'

plugin 'diffend'

gem 'karafka', '>= 2.0.0.alpha1'
gem 'rails', '~> 7.0'
gem 'sqlite3', '~> 1.4'
gem 'puma'

group :development, :test do
  gem 'karafka-testing', '>= 2.0.0.alpha1'
  gem 'rspec'
end
