# frozen_string_literal: true

source 'https://rubygems.org'

# plugin 'diffend'

gem 'dummy_kafka', path: 'gems/dummy_kafka'
gem 'puma'
gem 'rails', '~> 7.0'
gem 'sqlite3', '~> 1.4'

group :development, :test do
  gem 'pry'
  gem 'karafka-testing', '>= 2.0.0'
  gem 'rspec'
end
